var SHOP = {
  equipment: [
    { id:'magnifier_1', name:'精密放大镜Ⅰ', cost:15, prerequisite:null, icon:'🔍',
      desc:'放大镜使用次数 +1', effect:{ type:'magnifier', value:1 } },
    { id:'magnifier_2', name:'精密放大镜Ⅱ', cost:30, prerequisite:'magnifier_1', icon:'🔍',
      desc:'放大镜使用次数 +2（共+3）', effect:{ type:'magnifier', value:2 } },
    { id:'xray_1', name:'便携式X光机', cost:50, prerequisite:'magnifier_2', icon:'📡',
      desc:'扫描时显示物品类别（食品/电子产品等）', effect:{ type:'showCategory', value:true } },
    { id:'spectrum_1', name:'光谱分析仪', cost:80, prerequisite:'xray_1', icon:'🌈',
      desc:'扫描时直接标注风险等级', effect:{ type:'showRisk', value:true } }
  ],
  skills: [
    { id:'eagle_1', name:'鹰眼训练Ⅰ', cost:10, prerequisite:null, icon:'🦅',
      desc:'初始警觉 +5', effect:{ type:'initialAlarm', value:5 } },
    { id:'eagle_2', name:'鹰眼训练Ⅱ', cost:25, prerequisite:'eagle_1', icon:'🦅',
      desc:'初始警觉 +10（共+15）', effect:{ type:'initialAlarm', value:10 } },
    { id:'eagle_3', name:'鹰眼训练Ⅲ', cost:50, prerequisite:'eagle_2', icon:'🦅',
      desc:'初始警觉 +20（共+35）', effect:{ type:'initialAlarm', value:20 } },
    { id:'intuition_boost', name:'直觉强化', cost:20, prerequisite:null, icon:'🧠',
      desc:'单件扫描时间 -20%', effect:{ type:'scanSpeed', value:0.8 } },
    { id:'quick_react', name:'快速反应', cost:15, prerequisite:null, icon:'⚡',
      desc:'切换下一件行李时间 -1秒', effect:{ type:'transition', value:-1 } }
  ],
  intuitions: [
    { id:'crisis_exempt', name:'危机豁免', cost:25, prerequisite:null, icon:'🛡️',
      desc:'错误时20%概率不扣分', effect:{ type:'crisisExempt', chance:0.2 } },
    { id:'wind_warning', name:'风声预警', cost:30, prerequisite:null, icon:'🌪️',
      desc:'时间耗尽前5秒自动高亮走私品', effect:{ type:'windWarning', value:true } },
    { id:'adversity_rebound', name:'逆境反弹', cost:20, prerequisite:null, icon:'🔥',
      desc:'连续错2次后下次正确+5分', effect:{ type:'adversityRebound', value:5 } },
    { id:'time_mastery', name:'时间掌控', cost:35, prerequisite:null, icon:'⏳',
      desc:'时间耗尽时30%概率暂停5秒', effect:{ type:'timeMastery', chance:0.3 } },
    { id:'combo_keep', name:'连击延续', cost:25, prerequisite:null, icon:'💫',
      desc:'连击中断时30%概率保留', effect:{ type:'comboKeep', chance:0.3 } },
    { id:'lucky_bonus', name:'幸运加成', cost:40, prerequisite:null, icon:'🍀',
      desc:'周期结算额外+10%功勋', effect:{ type:'luckyBonus', value:0.1 } }
  ],
  knowledge: [
    { id:'k01', tutor:'linrui', name:'伪报品名', cost:15, icon:'📋',
      desc:'通关关卡初始警觉+2', effect:{ type:'tutorAlarm', tutor:'linrui', value:2 } },
    { id:'k02', tutor:'linrui', name:'伪报价格', cost:15, icon:'💰',
      desc:'通关关卡扫描时间+2秒', effect:{ type:'tutorTime', tutor:'linrui', value:2 } },
    { id:'k03', tutor:'linrui', name:'伪报数量', cost:15, icon:'📦',
      desc:'通关关卡错误惩罚-1', effect:{ type:'tutorPenalty', tutor:'linrui', value:-1 } },
    { id:'k04', tutor:'linrui', name:'瞒报夹藏', cost:15, icon:'🔍',
      desc:'通关关卡初始警觉+3', effect:{ type:'tutorAlarm', tutor:'linrui', value:3 } },
    { id:'k05', tutor:'linrui', name:'运输工具暗格', cost:20, icon:'🚛',
      desc:'通关关卡放大镜次数+1', effect:{ type:'tutorMagnifier', tutor:'linrui', value:1 } },
    { id:'k06', tutor:'linrui', name:'人体藏匿', cost:20, icon:'👤',
      desc:'通关关卡连击加成+1', effect:{ type:'tutorCombo', tutor:'linrui', value:1 } },

    { id:'k07', tutor:'chenfeng', name:'人体藏毒', cost:15, icon:'💊',
      desc:'毒品关卡初始警觉+2', effect:{ type:'tutorAlarm', tutor:'chenfeng', value:2 } },
    { id:'k08', tutor:'chenfeng', name:'行李夹藏毒品', cost:15, icon:'🧳',
      desc:'毒品关卡扫描时间+2秒', effect:{ type:'tutorTime', tutor:'chenfeng', value:2 } },
    { id:'k09', tutor:'chenfeng', name:'货物夹藏毒品', cost:15, icon:'📦',
      desc:'毒品关卡错误惩罚-1', effect:{ type:'tutorPenalty', tutor:'chenfeng', value:-1 } },
    { id:'k10', tutor:'chenfeng', name:'邮寄伪报毒品', cost:20, icon:'✉️',
      desc:'毒品关卡初始警觉+3', effect:{ type:'tutorAlarm', tutor:'chenfeng', value:3 } },
    { id:'k11', tutor:'chenfeng', name:'气味掩盖', cost:20, icon:'👃',
      desc:'毒品关卡放大镜次数+1', effect:{ type:'tutorMagnifier', tutor:'chenfeng', value:1 } },
    { id:'k12', tutor:'chenfeng', name:'新型毒品', cost:25, icon:'🧪',
      desc:'毒品关卡连击加成+1', effect:{ type:'tutorCombo', tutor:'chenfeng', value:1 } },

    { id:'k13', tutor:'zhaohai', name:'海上接驳', cost:15, icon:'🌊',
      desc:'海上关卡初始警觉+2', effect:{ type:'tutorAlarm', tutor:'zhaohai', value:2 } },
    { id:'k14', tutor:'zhaohai', name:'靠岸偷卸', cost:15, icon:'🏖️',
      desc:'海上关卡扫描时间+2秒', effect:{ type:'tutorTime', tutor:'zhaohai', value:2 } },
    { id:'k15', tutor:'zhaohai', name:'边境小道', cost:15, icon:'🛤️',
      desc:'海上关卡错误惩罚-1', effect:{ type:'tutorPenalty', tutor:'zhaohai', value:-1 } },
    { id:'k16', tutor:'zhaohai', name:'蚂蚁搬家', cost:20, icon:'🐜',
      desc:'海上关卡初始警觉+3', effect:{ type:'tutorAlarm', tutor:'zhaohai', value:3 } },
    { id:'k17', tutor:'zhaohai', name:'改装船舶', cost:20, icon:'⛵',
      desc:'海上关卡放大镜次数+1', effect:{ type:'tutorMagnifier', tutor:'zhaohai', value:1 } },
    { id:'k18', tutor:'zhaohai', name:'科技缉私', cost:25, icon:'🛰️',
      desc:'海上关卡连击加成+1', effect:{ type:'tutorCombo', tutor:'zhaohai', value:1 } },

    { id:'k19', tutor:'baiwei', name:'冻品绕关', cost:15, icon:'❄️',
      desc:'冻品关卡初始警觉+2', effect:{ type:'tutorAlarm', tutor:'baiwei', value:2 } },
    { id:'k20', tutor:'baiwei', name:'冻品伪报', cost:15, icon:'🥩',
      desc:'冻品关卡扫描时间+2秒', effect:{ type:'tutorTime', tutor:'baiwei', value:2 } },
    { id:'k21', tutor:'baiwei', name:'冻品夹藏', cost:15, icon:'🧊',
      desc:'冻品关卡错误惩罚-1', effect:{ type:'tutorPenalty', tutor:'baiwei', value:-1 } },
    { id:'k22', tutor:'baiwei', name:'冷链监控', cost:20, icon:'📡',
      desc:'冻品关卡初始警觉+3', effect:{ type:'tutorAlarm', tutor:'baiwei', value:3 } },
    { id:'k23', tutor:'baiwei', name:'疫病传播', cost:20, icon:'🦠',
      desc:'冻品关卡放大镜次数+1', effect:{ type:'tutorMagnifier', tutor:'baiwei', value:1 } },
    { id:'k24', tutor:'baiwei', name:'生物安全', cost:25, icon:'🌿',
      desc:'冻品关卡连击加成+1', effect:{ type:'tutorCombo', tutor:'baiwei', value:1 } },

    { id:'k25', tutor:'laozhou', name:'飞料走私', cost:15, icon:'🧵',
      desc:'加工关卡初始警觉+2', effect:{ type:'tutorAlarm', tutor:'laozhou', value:2 } },
    { id:'k26', tutor:'laozhou', name:'骗取核销', cost:15, icon:'📄',
      desc:'加工关卡扫描时间+2秒', effect:{ type:'tutorTime', tutor:'laozhou', value:2 } },
    { id:'k27', tutor:'laozhou', name:'串换料件', cost:15, icon:'🔬',
      desc:'加工关卡错误惩罚-1', effect:{ type:'tutorPenalty', tutor:'laozhou', value:-1 } },
    { id:'k28', tutor:'laozhou', name:'假结转', cost:20, icon:'🔄',
      desc:'加工关卡初始警觉+3', effect:{ type:'tutorAlarm', tutor:'laozhou', value:3 } },
    { id:'k29', tutor:'laozhou', name:'倒卖减免税', cost:20, icon:'🏷️',
      desc:'加工关卡放大镜次数+1', effect:{ type:'tutorMagnifier', tutor:'laozhou', value:1 } },
    { id:'k30', tutor:'laozhou', name:'假合作包税', cost:25, icon:'👜',
      desc:'加工关卡连击加成+1', effect:{ type:'tutorCombo', tutor:'laozhou', value:1 } },

    { id:'k31', tutor:'xiaohui', name:'珍贵动物制品', cost:15, icon:'🐘',
      desc:'综合关卡初始警觉+2', effect:{ type:'tutorAlarm', tutor:'xiaohui', value:2 } },
    { id:'k32', tutor:'xiaohui', name:'电子产品走私', cost:15, icon:'📱',
      desc:'综合关卡扫描时间+2秒', effect:{ type:'tutorTime', tutor:'xiaohui', value:2 } },
    { id:'k33', tutor:'xiaohui', name:'洋垃圾走私', cost:15, icon:'♻️',
      desc:'综合关卡错误惩罚-1', effect:{ type:'tutorPenalty', tutor:'xiaohui', value:-1 } },
    { id:'k34', tutor:'xiaohui', name:'全链条打击', cost:20, icon:'⚔️',
      desc:'综合关卡初始警觉+3', effect:{ type:'tutorAlarm', tutor:'xiaohui', value:3 } },
    { id:'k35', tutor:'xiaohui', name:'国际协作', cost:20, icon:'🤝',
      desc:'综合关卡放大镜次数+1', effect:{ type:'tutorMagnifier', tutor:'xiaohui', value:1 } },
    { id:'k36', tutor:'xiaohui', name:'缉私精神', cost:30, icon:'🌟',
      desc:'所有关卡初始警觉+2', effect:{ type:'globalAlarm', value:2 } }
  ]
};

var SHOP_QUIZ = {
  k01:{q:[{q:'将高税率商品伪报为低税率商品属于？',a:['伪报品名','伪报价格','瞒报夹藏'],c:0},{q:'伪报品名的识别要点是？',a:['包装精美','品名模糊','价格合理'],c:1},{q:'反制伪报的手段是？',a:['加税','HS编码比对','销毁货物'],c:1}]},
  k02:{q:[{q:'故意低报进口价格属于？',a:['伪报数量','伪报价格','瞒报夹藏'],c:1},{q:'伪报价格常通过哪种方式？',a:['关联交易','水客夹带','蚂蚁搬家'],c:0},{q:'海关估价系统的作用是？',a:['加快通关','比对市场价格','销毁货物'],c:1}]},
  k03:{q:[{q:'少报多进属于什么手法？',a:['伪报数量','伪报价格','伪报品名'],c:0},{q:'识别伪报数量的关键线索？',a:['包装颜色','重量与数量不匹配','价格高低'],c:1},{q:'反制伪报数量的手段？',a:['称重查验','加税','销毁'],c:0}]},
  k04:{q:[{q:'在合法货物中隐藏走私品属于？',a:['瞒报夹藏','伪报品名','人体藏匿'],c:0},{q:'识别夹藏的有效设备是？',a:['温度计','X光机','称重秤'],c:1},{q:'夹藏案件中最常用的反制手段？',a:['随机开箱','加税','禁止进口'],c:0}]},
  k05:{q:[{q:'运输工具暗格指什么？',a:['车内装饰','设置的隐蔽夹层','货物包装'],c:1},{q:'识别暗格的有效方法？',a:['看颜色','结构检查+重量分析','闻气味'],c:1},{q:'暗格走私的常见改装部位？',a:['座椅','双层底板','车窗'],c:1}]},
  k06:{q:[{q:'人体藏匿指什么？',a:['绑在身上或藏在体内','藏在行李中','藏在货物中'],c:0},{q:'识别人体藏匿的方法？',a:['测体温','体态+出入境记录','问话'],c:1},{q:'反制人体藏匿的设备？',a:['金属探测器','毫米波扫描仪','测谎仪'],c:1}]},
  k07:{q:[{q:'人体藏毒的携带方式？',a:['吞服胶囊','放在口袋','贴在鞋底'],c:0},{q:'人体藏毒的特征？',a:['神色正常','腹部肿胀','行李很多'],c:1},{q:'反制人体藏毒的手段？',a:['X光扫描','搜包','测体温'],c:0}]},
  k08:{q:[{q:'昆明裙子藏毒案藏了多少克？',a:['500克','1843克','3000克'],c:1},{q:'识别行李夹藏的关键？',a:['颜色','重量异常','品牌'],c:1},{q:'反制行李夹藏的手段？',a:['缉毒犬+X光','只查可疑人','测温度'],c:0}]},
  k09:{q:[{q:'净水器藏毒案藏的是什么毒品？',a:['海洛因','冰毒','大麻'],c:1},{q:'货物夹藏毒品的特点？',a:['结构异常','包装精美','重量轻'],c:0},{q:'反制货物夹藏的手段？',a:['肉眼观察','化学快检','测温度'],c:1}]},
  k10:{q:[{q:'邮寄伪报毒品常用什么伪装？',a:['"茶叶"包裹','"玩具"包裹','"书籍"包裹'],c:0},{q:'识别邮寄毒品的线索？',a:['包装大小','寄件人信息可疑','邮票颜色'],c:1},{q:'反制邮寄毒品的手段？',a:['邮包X光扫描','退回邮件','加邮费'],c:0}]},
  k11:{q:[{q:'气味掩盖手法的目的是？',a:['让货物好闻','逃避缉毒犬','保鲜'],c:1},{q:'气味掩盖的典型案例？',a:['辣椒粉藏毒','面粉藏毒','水藏毒'],c:0},{q:'反制气味掩盖的手段？',a:['闻气味','化学检测','加热'],c:1}]},
  k12:{q:[{q:'新型毒品常伪装成什么？',a:['保健品和电子烟油','水果','饮料'],c:0},{q:'全球已发现多少新精神活性物质？',a:['超100种','超1000种','超10000种'],c:1},{q:'反制新型毒品的手段？',a:['化学快检','肉眼辨别','大众举报'],c:0}]},
  k13:{q:[{q:'海上接驳指什么？',a:['渔船加油','船舶海上交接货物','靠岸卸货'],c:1},{q:'识别海上接驳的线索？',a:['白天作业','夜间异常活动','鸣笛声'],c:1},{q:'反制海上接驳的手段？',a:['雷达监控','拦截所有船','禁海'],c:0}]},
  k14:{q:[{q:'靠岸偷卸的常用地点？',a:['大港口','偏远海滩码头','市中心'],c:1},{q:'识别靠岸偷卸的线索？',a:['白天卸货','夜间车辆聚集','正规报关'],c:1},{q:'反制靠岸偷卸的手段？',a:['海岸监控','封海','禁渔'],c:0}]},
  k15:{q:[{q:'边境小道走私的运输方式？',a:['飞机','步行或车辆','轮船'],c:1},{q:'识别边境小道走私的线索？',a:['正规边贸','异常足迹车辙','旅游'],c:1},{q:'反制边境小道的手段？',a:['热成像监控','封关','取消签证'],c:0}]},
  k16:{q:[{q:'"蚂蚁搬家"的特点？',a:['单次量大','频次高单次量小','单次量大频次低'],c:1},{q:'识别蚂蚁搬家的方法？',a:['查行李重量','分析出入境频次','测身高'],c:1},{q:'反制蚂蚁搬家的手段？',a:['布控重点人员','禁行','收税'],c:0}]},
  k17:{q:[{q:'改装船舶的常见手法？',a:['改颜色','加装暗格暗舱','换引擎'],c:1},{q:'识别改装船舶的线索？',a:['船体干净','吃水线异常','船速快'],c:1},{q:'反制改装船舶的手段？',a:['船舶检查','限速','禁航'],c:0}]},
  k18:{q:[{q:'查船机器人的监管半径是多少？',a:['3km','25km','100km'],c:1},{q:'科技缉私使查获率提升多少？',a:['20%','40%','60%'],c:1},{q:'下列哪项是科技缉私手段？',a:['望远镜','卫星遥感','人工巡逻'],c:1}]},
  k19:{q:[{q:'冻品绕关的风险是什么？',a:['不新鲜','未经检疫可能带疫病','价格高'],c:1},{q:'识别冻品绕关的线索？',a:['包装精美','无中文标签无检疫证','冷链完整'],c:1},{q:'反制冻品绕关的手段？',a:['冷链监控','加税','禁运'],c:0}]},
  k20:{q:[{q:'冻品伪报的常见做法？',a:['冻牛肉伪报冷冻食品','冻牛肉如实申报','冻牛肉加价申报'],c:0},{q:'识别冻品伪报的关键？',a:['包装大小','包装与品名不符','生产日期'],c:1},{q:'反制冻品伪报的手段？',a:['开箱查验','重量检查','颜色检查'],c:0}]},
  k21:{q:[{q:'冻品夹藏指什么？',a:['合法冻品掺走私冻品','全部走私','全部合法'],c:0},{q:'识别冻品夹藏的线索？',a:['包装统一','包装混杂温度异常','来源单一'],c:1},{q:'反制冻品夹藏的手段？',a:['检疫核查','加税','禁运'],c:0}]},
  k22:{q:[{q:'冷链监控不包括哪项？',a:['GPS追踪','温度记录','货物颜色检测'],c:2},{q:'冷链监控的效果？',a:['冻品查获率+35%','成本降低','速度提升'],c:0},{q:'冷链监控的电子锁作用？',a:['防偷换','防盗','防丢失'],c:0}]},
  k23:{q:[{q:'非洲猪瘟通过什么渠道传入？',a:['空气','走私猪肉','海水'],c:1},{q:'疫病传播造成的损失？',a:['100万元','1000亿元','无损失'],c:1},{q:'防控疫病传播的手段？',a:['来源国禁令','加税','消毒'],c:0}]},
  k24:{q:[{q:'中国已发现多少外来入侵物种？',a:['超100种','超660种','超1000种'],c:1},{q:'国门生物安全的第一道防线是？',a:['境内监测','口岸检疫','应急处置'],c:1},{q:'红火蚁是通过什么传入的？',a:['空气','木质包装','土壤'],c:1}]},
  k25:{q:[{q:'飞料走私指什么？',a:['保税料件不加工直接内销','货物飞起来','快速通关'],c:0},{q:'识别飞料走私的线索？',a:['用电量与产能不匹配','产量高','用电量大'],c:0},{q:'反制飞料走私的手段？',a:['联网监管','加税','暂停贸易'],c:0}]},
  k26:{q:[{q:'骗取核销的手段？',a:['虚报出口数量','如实申报','少报出口'],c:0},{q:'识别骗取核销的关键？',a:['核销数据与物流不符','数据一致','价格合理'],c:0},{q:'反制骗取核销的手段？',a:['数据比对','加税','禁止出口'],c:0}]},
  k27:{q:[{q:'串换料件指什么？',a:['国产替换进口保税料件','进口替换国产','正常使用'],c:0},{q:'识别串换料件的线索？',a:['产品质量不符','包装精美','价格合理'],c:0},{q:'反制串换料件的手段？',a:['质量检测','加税','禁止加工'],c:0}]},
  k28:{q:[{q:'假结转指什么？',a:['真实交易','虚假深加工结转','正常物流'],c:1},{q:'识别假结转的线索？',a:['物流记录完整','无实际物流','价格合理'],c:1},{q:'反制假结转的手段？',a:['物流核查','加税','禁止结转'],c:0}]},
  k29:{q:[{q:'倒卖减免税指什么？',a:['设备转卖无资格企业','设备正常使用','设备报废'],c:0},{q:'识别倒卖减免税的线索？',a:['设备在非申请企业','设备正常使用','设备已报废'],c:0},{q:'反制倒卖减免税的手段？',a:['全生命周期监管','加税','没收'],c:0}]},
  k30:{q:[{q:'假合作包税指什么？',a:['借用企业名义进口','合作经营','正常包税'],c:0},{q:'识别假合作包税的线索？',a:['进口与使用企业不一致','企业一致','价格合理'],c:0},{q:'反制假合作包税的手段？',a:['资质核查','加税','禁运'],c:0}]},
  k31:{q:[{q:'象牙的鉴别特征是什么？',a:['光滑表面','施雷格线交叉纹路','颜色'],c:1},{q:'CITES公约是什么？',a:['贸易公约','濒危物种国际贸易公约','海关公约'],c:1},{q:'反制珍贵动物制品走私的手段？',a:['CITES证书核查','加税','销毁'],c:0}]},
  k32:{q:[{q:'电子产品走私的常见方式？',a:['整机报为配件','如实申报','邮寄'],c:0},{q:'识别电子产品走私的线索？',a:['无3C认证','包装精美','价格合理'],c:0},{q:'反制电子产品走私的手段？',a:['认证核查','加税','禁运'],c:0}]},
  k33:{q:[{q:'洋垃圾走私包括什么？',a:['废塑料医疗废物','全新商品','二手正品'],c:0},{q:'中国何时全面禁止洋垃圾入境？',a:['2018年','2021年起','2023年'],c:1},{q:'反制洋垃圾走私的手段？',a:['属性鉴定','加税','回收'],c:0}]},
  k34:{q:[{q:'全链条打击的目标？',a:['只打源头','走私到销售全环节','只打销售'],c:1},{q:'全链条打击的效果？',a:['复发率降低60%','复发率不变','复发率升高'],c:0},{q:'"国门之盾"行动摧毁了多大案值？',a:['4.7亿元','1亿元','10亿元'],c:0}]},
  k35:{q:[{q:'国际协作不包括哪项？',a:['情报交换','单边行动','联合执法'],c:1},{q:'中国与多少国家建立海关合作？',a:['50多个','100多个','200多个'],c:1},{q:'国际协作的效果？',a:['查获率提升30%','查获率不变','查获率降低'],c:0}]},
  k36:{q:[{q:'缉私精神的内涵？',a:['忠诚勇敢智慧奉献','勇敢赚钱','智慧发财'],c:0},{q:'缉私科技从什么到什么？',a:['望远镜到查船机器人','算盘到电脑','电话到手机'],c:0},{q:'导师的寄望是什么？',a:['每次任务平安归来','多查案','多立功'],c:0}]}
};

var TUTOR_NAMES = { linrui:'林锐', chenfeng:'陈锋', zhaohai:'赵海', baiwei:'白薇', laozhou:'老周', xiaohui:'小辉' };
